name: CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: arm
            goarm: 5
          - arch: arm
            goarm: 7
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: '1.16'
      - run: go build ./...
        env:
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.goarm }}
  test:
    runs-on: 'windows-2019'
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: '1.16'
      - run: go test ./...
