name: CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: arm
            goarm: 5
          - arch: arm
            goarm: 7
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.16'
      - run: go build ./...
        env:
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.goarm }}
  test:
    runs-on: 'windows-2022'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.16'
      - run: go test ./...
