name: CI
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        include:
          - arch: amd64
          - arch: arm
            goarm: 5
          - arch: arm
            goarm: 7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go build ./...
        env:
          GOOS: windows
          GOARCH: ${{ matrix.arch }}
          GOARM: ${{ matrix.goarm }}
  test:
    runs-on: 'windows-2019'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: go test ./...
